#ifndef GAME_CONFIG_H
#define GAME_CONFIG_H

#define SCREEN_WIDTH 720
#define SCREEN_HEIGHT 1280
#define GAME_AREA_WIDTH 1000
#define GAME_AREA_HEIGHT 1000

#define BALLOON_RADIUS 30
#define OBSTACLE_WIDTH 60
#define OBSTACLE_HEIGHT 50
#define GROUND_HEIGHT 40
#define GAME_SPEED 8
#define MAX_HEIGHT 10000
#define RECORD_LENGTH 320

#define BALLOON_COLOR TFT_RED
#define OBSTACLE_COLOR TFT_GREEN
#define GROUND_COLOR TFT_BROWN
#define BACKGROUND_COLOR TFT_SKYBLUE
#define TEXT_COLOR TFT_WHITE
#define GAME_OVER_COLOR TFT_RED
#define TITLE_COLOR TFT_BLUE
#define BURST_COLOR TFT_YELLOW

#define TITLE_FONT_SIZE 3
#define GAME_FONT_SIZE 2
#define UI_FONT_SIZE 2

#define MIC_THRESHOLD 1000
#define BLOW_DURATION 500
#define RECORD_SAMPLERATE 17000

// Waveform display settings
#define WAVE_POS_Y 60
#define WAVE_HEIGHT 50
#define WAVE_COLOR TFT_WHITE
#define WAVE_SHIFT 6

// Level design settings
#define LEVEL_HEIGHT_STEP 300
#define LEVEL_UP_COLOR TFT_YELLOW
#define LEVEL_UP_FONT_SIZE 4
#define LEVEL_UP_DURATION 1500
#define MAX_LEVEL 10
#define BASE_OBSTACLE_INTERVAL 1500
#define MIN_OBSTACLE_INTERVAL 600

#endif
